development:
  adapter: postgresql
  encoding: unicode
  database: dsi_class_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: dsi_class_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: dsi_class_production
  pool: 5
