# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0a7c02f9664baf26f26adcd0ead84a8479b88377fc06743937bdd3a70fea366205edbb659a762b5b112c53a6af0d7b93022929d1f2fc4a55078594326ec96c6

test:
  secret_key_base: 4a0796b3f12823e6426439ddd00d34588de14706c427aff90f227df90121ddda60414493d5a0fbedd002e50783eae620bed978731756a3b5514c85a86ba051f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
